# https://metallb.universe.tf/configuration/#layer-2-configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
      - name: kind
        protocol: layer2
        addresses:
          - 172.17.1.11-172.17.1.100
